### ISSUE TITLE
How to remove arrow from leaf node?

### ISSUE THREAD

**Issue by himanshu-patidar** [garrettheel/angular-treetable#5]

**Comment by garrettheel** [comment]
You shouldn't have an arrow if you set `is-branch` correctly on your `tt-node` element.

E.g `<tr tt-node is-branch="node.type == 'folder'">`

See https://github.com/GarrettHeel/angular-treetable/blob/master/example/example.html

**Comment by himanshu-patidar** [comment]
Thanks for reply. It is working fine.
