### ISSUE TITLE
Expand a Node

### ISSUE THREAD

**Issue by haffo** [garrettheel/angular-treetable#6]
Hi,
Do you currently have a way to expand a node and its children of the fly ? 

Thanks

**Comment by garrettheel** [comment]
Do you mean that you'd like to open a node programmatically rather than only when a user clicks on one?

If you could let me know your use-case that would be helpful!

**Comment by haffo** [comment]
Hi Garrett, 
I have a very long tree and it is cumbersome to have to open each node and its children one by one. I want to have a check box on each row to programmatically expand/collapse a node and its children. Is that possible ?  Thanks

**Comment by garrettheel** [comment]
This is possible using the underlying [API](http://ludo.cubicphuse.nl/jquery-treetable/). For example, the following will expand the first node in `examples/examples.html`:

``` javascript
$($('table')[0]).treetable('expandNode', 0);  // the 0 argument to expandNode is the node ID
```

You can explore the tree to find out which IDs to expand by starting from the root (`$($('table')[0]).data().treetable.tree`) or from a specific node (`$($('tr')[1]).data().ttId`).

So while it's _possible_ using these things, it could be exposed in a much nicer way through this library. If you have some idea of what you'd like the Angular API to look like for doing this I'll look at building it.

Hope that helps!

**Comment by Tandzone** [comment]
wow! thanks!
